name: Test
on:
  push:
    branches-ignore:
      - gh-pages
env:
  NODE_ENV: test
jobs:
  install-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Test 🔧
        run: |
          yarn install
          yarn test
      - name: Clean 🧹
        run: |
          yarn clean:all
      - name: OpenShift S2I Build 🚀
        if: ${{ github.repository == 'bcgov/NotifyBC' }}
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL}}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'whoami'
            'start-build notify-bc --from-dir=. -Fw -n ${{ secrets.OPENSHIFT_PROJECT }}-tools'
            'tag ${{ secrets.OPENSHIFT_PROJECT }}-tools/notify-bc:latest ${{ secrets.OPENSHIFT_PROJECT }}-dev/notify-bc:latest -n ${{ secrets.OPENSHIFT_PROJECT }}-tools'
